### ISSUE TITLE
Wrong formula used to calculate dew point

### ISSUE THREAD

**Issue by dex6** [drohm/pi-sht1x#20]
Hello,
I've been writing my own minidriver for SHT11, and noticed dew point calculation is wrong here.

This line:
https://github.com/drohm/pi-sht1x/blob/ea8b5bcd9bc5ffa37b1d6115727148ab99f6e572/pi_sht1x/sht1x.py#L232
does not agree with formula in the SHT1x datasheet:
![image](https://user-images.githubusercontent.com/5950550/158454185-94303443-1770-434b-bb2a-ca090dca68f4.png)

Instead of `... / m - (log_humidity + ew)`, it should be `... / (m - log_humidity - ew)` in the denominator.
(Alternatively, `... / (m - (log_humidity + ew))` is also okay.)

**Comment by drohm** [comment]
Thanks @dex6.  I've updated the file with the fix you listed.  I'm waiting on another merge request to finish up. Once that does, I'll do a new build and publish up to PyPI.  Thanks for spotting that.

**Comment by dex6** [comment]
`tn * ((log_humidity + ew) / m - (log_humidity - ew))`

I think this is still wrong; denominator should include all three terms, not just m. So one ( should be earlier:

`tn * ((log_humidity + ew) / (m - log_humidity - ew))`

**Comment by drohm** [comment]
Thanks @dex6, fixed the parens and pushed.
