### ISSUE TITLE
Stopping re-setting of GPIO's

### ISSUE THREAD

**Issue by crannog1** [drohm/pi-sht1x#4]
Hi,

I'm using the SHT1x module in a weather station program. Unfortunately it appears to reset GPIO's and GPIO.setmode which is effecting the main program. I've deleted the GPIO.cleanup() but I still get same problem.
can you help?

Thanks

Donall

**Comment by drohm** [comment]
Hi, can you give me some information on how you're using it and what else you have running?  I'm assuming you have other sensors for the station, but are they all running at the same time or do you have them take readings one after another (synchronously)?  Any background on how your weather station works would help to debug this.

**Comment by crannog1** [comment]
Hi,

I have a main program that cycles every second to get measurements from the senors and write to a file. The main program calls each sub-routine in turn, waits for 1 second to complete then cycles back around again. 

The GPIOsetmode is set to BCM and pins assigned at start of program then it moves to measurement loop to get readings each second. It appears that after calling on temp/humidity sensor, the GPIO's get re-set and program crashes.
