### ISSUE TITLE
sensor.py TypeError

### ISSUE THREAD

**Issue by elysio2** [drohm/pi-sht1x#7]
TypeError: **init**() got an unexpected keyword argument 'logger'

**Comment by drohm** [comment]
@elysio2 Can you give more details in how you got that error?  Was that on install?  Was it when you tried to take a temp reading?  Any details you can give help in debugging the issue.  Thanks.

**Comment by elysio2** [comment]
@drohm Simply running the sensor.py file after a pip3 install makes this error. examples.py still works, as well as any custom code.

```
 File "sensor.py", line 46, in main
    logger=logger) as sensor:
```

**Comment by drohm** [comment]
Thanks @elysio2. Can you give details on how you're invoking sensor.py versus the examples.py?

**Comment by elysio2** [comment]
@drohm 
sensor.py : `sudo python3 sensor.py 18 23`
examples.py : `sudo python3 temp2.py`

(temp2.py is a copy/paste of examples.py)

**Comment by drohm** [comment]
The sensor.py isn't meant to be invoked that way.  If you browse through the README, you'll see you can make calls like this:

```
from pi_sht1x import SHT1x

with SHT1x(18, 23, gpio_mode=GPIO.BCM) as sensor:
    temp = sensor.read_temperature()
    humidity = sensor.read_humidity(temp)
    sensor.calculate_dew_point(temp, humidity)
    print(sensor)
```

Give that a try and let me know.

**Comment by elysio2** [comment]
That works , but FYI the readme clearly states

## 

**sensor.py**

This script is callable from the terminal and the sensor parameters are passed into the script.

`sudo python3 sensor.py 18 23 -g 'BCM'`

This executes the sensor script using data_pin=18, sck_pin=23, and gpio_mode=GPIO.BCM. The script will then create an instance of the SHT1x class and read in the temperature, humidity, and calculate the dew point five times, sleeping 2 seconds in between each measurement.

## 

I was only using this for testing purposes when I forgot the 10k pull-up resistor, just thought  you should know.

**Comment by drohm** [comment]
@elysio2 Ahh, okay.  I'll dig into this later today and update the README accordingly.  Thanks for bringing this up.

**Comment by drohm** [comment]
@elysio2 What version of the pi-sht1x library is installed?  If you could look at the SHT1x class, could you confirm that the version installed on your system has the `logger` parameter defined in the `__init__()` method?
